// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include <Windows.h>
#include <cassert>
#include <tchar.h>
#include "patcher.h"

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define MESSAGE_RAISE_LOCATION __FILE__ "(" TOSTRING(__LINE__) "): "

extern "C"
{
    // fill original library path here
    // use absolute file path
    void GetOrignalLibraryPath(TCHAR* bufferPtr, int bufferLength, const TCHAR* libName)
    {
        assert(bufferPtr != nullptr);
        assert(libName != nullptr);

        GetSystemDirectory(bufferPtr, bufferLength);
        lstrcat(bufferPtr, TEXT("\\"));
        lstrcat(bufferPtr, libName);
    }


    // apply use custom operation
    void __ExecuteUserCutomCodes()
    {
        doFuckKook();
    }

    int __CheckShouldExecuteAttachCode()
    {
        return 1;
    }
}
