// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#pragma once

#ifndef  __cplusplus
#error "this header i created for C++ only."
#endif

#include <windows.h>

#include <vector>
#include <string>

struct MemoryPatchConfig
{
    std::string ModuleName;
    std::string SegmentName;
    std::vector<BYTE> Signature;
    std::vector<BYTE> NewBytes;

    void Reset()
    {
        ModuleName.clear();
        SegmentName.clear();
        Signature.clear();
        NewBytes.clear();
    }

    bool IsValid() const
    {
        return !SegmentName.empty() && !Signature.empty() && NewBytes.size() == Signature.size();
    }
};

class MemoryPatchConfigParser
{
public:
    MemoryPatchConfigParser(const char* text);

    const std::vector<MemoryPatchConfig>& GetConfigurations() const{ return Configurations; }

    std::vector<MemoryPatchConfig> TakeConfigurations()
    {
        return std::move(Configurations);
    }

private:
    std::string GetName(const std::string& text);
    std::vector<BYTE> GetBytes(const std::string& text);
private:
    std::vector<MemoryPatchConfig>  Configurations;
};

void PatchMemoryWithConfig(const std::vector<MemoryPatchConfig>& configs);

std::string LoadTextResource(int resourceId);
std::vector<MemoryPatchConfig> LoadConfigurations(int resourceId);

std::string LoadFileConfigText();
std::string LoadFileContent(const TCHAR* path);

std::vector<MemoryPatchConfig> LoadFileConfigurations();


