// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include "MemoryPatchConfig.h"
#include "resource.h"
#include <cassert>
#include <string>

extern "C"
{
    static void __ApplyResourceBasedPatches()
    {
        auto configs = LoadConfigurations(IDR_TXT2);

        if (!configs.empty())
        {
            PatchMemoryWithConfig(configs);
        }
    }

    static void __ApplyFileBasedPatches()
    {
        auto configs = LoadFileConfigurations();

        if (!configs.empty())
        {
            PatchMemoryWithConfig(configs);
        }
    }

    // apply patches based on resource text files
    void __ApplyBuiltinPatches()
    {
        __ApplyResourceBasedPatches();
        __ApplyFileBasedPatches();
    }
}
