// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include <windows.h>
#include "MiniTools.h"

#if defined(_WIN64) || defined(_X64) || defined(WIN64) || defined( __LP64__ )
#define __X64_BUILD__ 1
#else
#define __X64_BUILD__ 0
#endif

// checked get function in native dll
static void* __CheckedGetFunction(HMODULE module, const char* methodName)
{
    void* Result = GetProcAddress(module, methodName);

    if (Result == NULL)
    {
        char szMessage[256];
        wsprintfA(szMessage, "Failed bind method:%s", methodName);

        OutputDebugStringA(szMessage);

#if DEBUG
        MessageBoxA(0, szMessage, "AHeadLib.Net Error", 0);
        ExitProcess(-1);
#endif
    }

    return Result;
}

void* AlphaBlendPtr = NULL;
void* DllInitializePtr = NULL;
void* GradientFillPtr = NULL;
void* TransparentBltPtr = NULL;
void* vSetDdrawflagPtr = NULL;

extern void WINAPI ASM_AlphaBlend();
extern void WINAPI ASM_DllInitialize();
extern void WINAPI ASM_GradientFill();
extern void WINAPI ASM_TransparentBlt();
extern void WINAPI ASM_vSetDdrawflag();

#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:AlphaBlend=ASM_AlphaBlend")
#else
#pragma comment(linker, "/EXPORT:AlphaBlend=_ASM_AlphaBlend@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:DllInitialize=ASM_DllInitialize")
#else
#pragma comment(linker, "/EXPORT:DllInitialize=_ASM_DllInitialize@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GradientFill=ASM_GradientFill")
#else
#pragma comment(linker, "/EXPORT:GradientFill=_ASM_GradientFill@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:TransparentBlt=ASM_TransparentBlt")
#else
#pragma comment(linker, "/EXPORT:TransparentBlt=_ASM_TransparentBlt@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:vSetDdrawflag=ASM_vSetDdrawflag")
#else
#pragma comment(linker, "/EXPORT:vSetDdrawflag=_ASM_vSetDdrawflag@8")
#endif

// bind native dll first
extern void GetOrignalLibraryPath(TCHAR* bufferPtr, int bufferLength, const TCHAR* libName);

void __CheckedLoad()
{
    TCHAR szPath[MAX_PATH];

    GetOrignalLibraryPath(szPath, MAX_PATH, TEXT("msimg32.dll"));

    // if your dll is not in system path
    // please reset szPath here
    HMODULE module = LoadLibrary(szPath);

    if (module == NULL)
    {
        TCHAR szMessage[MAX_PATH];
        wsprintf(szMessage, TEXT("Failed load dll from:%s"), szPath);
        ShowMessageBox(0, szMessage, TEXT("AHeadLib.Net Error"), 0);
        
        ExitProcess(1);
        return;
    }

    AlphaBlendPtr = __CheckedGetFunction(module, "AlphaBlend");
    DllInitializePtr = __CheckedGetFunction(module, "DllInitialize");
    GradientFillPtr = __CheckedGetFunction(module, "GradientFill");
    TransparentBltPtr = __CheckedGetFunction(module, "TransparentBlt");
    vSetDdrawflagPtr = __CheckedGetFunction(module, "vSetDdrawflag");
}


