; generated by tools
; AHeadLib.Net
; https://github.com/bodong1987/AHeadLib.Net
; Powered by bodong

.MODEL FLAT

.DATA
    EXTERNDEF _AlphaBlendPtr:DWORD
    EXTERNDEF _DllInitializePtr:DWORD
    EXTERNDEF _GradientFillPtr:DWORD
    EXTERNDEF _TransparentBltPtr:DWORD
    EXTERNDEF _vSetDdrawflagPtr:DWORD

.CODE

_ASM_AlphaBlend@8 PROC
    jmp DWORD PTR [_AlphaBlendPtr]
_ASM_AlphaBlend@8 ENDP

_ASM_DllInitialize@8 PROC
    jmp DWORD PTR [_DllInitializePtr]
_ASM_DllInitialize@8 ENDP

_ASM_GradientFill@8 PROC
    jmp DWORD PTR [_GradientFillPtr]
_ASM_GradientFill@8 ENDP

_ASM_TransparentBlt@8 PROC
    jmp DWORD PTR [_TransparentBltPtr]
_ASM_TransparentBlt@8 ENDP

_ASM_vSetDdrawflag@8 PROC
    jmp DWORD PTR [_vSetDdrawflagPtr]
_ASM_vSetDdrawflag@8 ENDP


END

