; generated by tools
; AHeadLib.Net
; https://github.com/bodong1987/AHeadLib.Net
; Powered by bodong

.DATA
    EXTERNDEF AlphaBlendPtr:QWORD
    EXTERNDEF DllInitializePtr:QWORD
    EXTERNDEF GradientFillPtr:QWORD
    EXTERNDEF TransparentBltPtr:QWORD
    EXTERNDEF vSetDdrawflagPtr:QWORD

.CODE

ASM_AlphaBlend PROC
    jmp [AlphaBlendPtr]
ASM_AlphaBlend ENDP

ASM_DllInitialize PROC
    jmp [DllInitializePtr]
ASM_DllInitialize ENDP

ASM_GradientFill PROC
    jmp [GradientFillPtr]
ASM_GradientFill ENDP

ASM_TransparentBlt PROC
    jmp [TransparentBltPtr]
ASM_TransparentBlt ENDP

ASM_vSetDdrawflag PROC
    jmp [vSetDdrawflagPtr]
ASM_vSetDdrawflag ENDP


END

