// generated by tools
// AHeadLib.Net
// https://github.com/bodong1987/AHeadLib.Net
// Powered by bodong

#include <windows.h>

#if defined(_WIN64) || defined(_X64) || defined(WIN64) || defined( __LP64__ )
#define __X64_BUILD__ 1
#else
#define __X64_BUILD__ 0
#endif

// checked get function in native dll
static void* __CheckedGetFunction(HMODULE module, const char* methodName)
{
    void* Result = GetProcAddress(module, methodName);

    if (Result == NULL)
    {
        char szMessage[256];
        wsprintfA(szMessage, "Failed bind method:%s", methodName);

        OutputDebugStringA(szMessage);

#if DEBUG
        MessageBoxA(0, szMessage, "AHeadLib.Net Error", 0);
        ExitProcess(-1);
#endif
    }

    return Result;
}

void* GetFileVersionInfoAPtr = NULL;
void* GetFileVersionInfoByHandlePtr = NULL;
void* GetFileVersionInfoExAPtr = NULL;
void* GetFileVersionInfoExWPtr = NULL;
void* GetFileVersionInfoSizeAPtr = NULL;
void* GetFileVersionInfoSizeExAPtr = NULL;
void* GetFileVersionInfoSizeExWPtr = NULL;
void* GetFileVersionInfoSizeWPtr = NULL;
void* GetFileVersionInfoWPtr = NULL;
void* VerFindFileAPtr = NULL;
void* VerFindFileWPtr = NULL;
void* VerInstallFileAPtr = NULL;
void* VerInstallFileWPtr = NULL;
void* VerLanguageNameAPtr = NULL;
void* VerLanguageNameWPtr = NULL;
void* VerQueryValueAPtr = NULL;
void* VerQueryValueWPtr = NULL;

extern void WINAPI ASM_GetFileVersionInfoA();
extern void WINAPI ASM_GetFileVersionInfoByHandle();
extern void WINAPI ASM_GetFileVersionInfoExA();
extern void WINAPI ASM_GetFileVersionInfoExW();
extern void WINAPI ASM_GetFileVersionInfoSizeA();
extern void WINAPI ASM_GetFileVersionInfoSizeExA();
extern void WINAPI ASM_GetFileVersionInfoSizeExW();
extern void WINAPI ASM_GetFileVersionInfoSizeW();
extern void WINAPI ASM_GetFileVersionInfoW();
extern void WINAPI ASM_VerFindFileA();
extern void WINAPI ASM_VerFindFileW();
extern void WINAPI ASM_VerInstallFileA();
extern void WINAPI ASM_VerInstallFileW();
extern void WINAPI ASM_VerLanguageNameA();
extern void WINAPI ASM_VerLanguageNameW();
extern void WINAPI ASM_VerQueryValueA();
extern void WINAPI ASM_VerQueryValueW();

#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoA=ASM_GetFileVersionInfoA")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoA=_ASM_GetFileVersionInfoA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoByHandle=ASM_GetFileVersionInfoByHandle")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoByHandle=_ASM_GetFileVersionInfoByHandle@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExA=ASM_GetFileVersionInfoExA")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExA=_ASM_GetFileVersionInfoExA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExW=ASM_GetFileVersionInfoExW")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoExW=_ASM_GetFileVersionInfoExW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeA=ASM_GetFileVersionInfoSizeA")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeA=_ASM_GetFileVersionInfoSizeA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExA=ASM_GetFileVersionInfoSizeExA")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExA=_ASM_GetFileVersionInfoSizeExA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExW=ASM_GetFileVersionInfoSizeExW")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeExW=_ASM_GetFileVersionInfoSizeExW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeW=ASM_GetFileVersionInfoSizeW")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoSizeW=_ASM_GetFileVersionInfoSizeW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:GetFileVersionInfoW=ASM_GetFileVersionInfoW")
#else
#pragma comment(linker, "/EXPORT:GetFileVersionInfoW=_ASM_GetFileVersionInfoW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerFindFileA=ASM_VerFindFileA")
#else
#pragma comment(linker, "/EXPORT:VerFindFileA=_ASM_VerFindFileA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerFindFileW=ASM_VerFindFileW")
#else
#pragma comment(linker, "/EXPORT:VerFindFileW=_ASM_VerFindFileW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerInstallFileA=ASM_VerInstallFileA")
#else
#pragma comment(linker, "/EXPORT:VerInstallFileA=_ASM_VerInstallFileA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerInstallFileW=ASM_VerInstallFileW")
#else
#pragma comment(linker, "/EXPORT:VerInstallFileW=_ASM_VerInstallFileW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerLanguageNameA=ASM_VerLanguageNameA")
#else
#pragma comment(linker, "/EXPORT:VerLanguageNameA=_ASM_VerLanguageNameA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerLanguageNameW=ASM_VerLanguageNameW")
#else
#pragma comment(linker, "/EXPORT:VerLanguageNameW=_ASM_VerLanguageNameW@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerQueryValueA=ASM_VerQueryValueA")
#else
#pragma comment(linker, "/EXPORT:VerQueryValueA=_ASM_VerQueryValueA@8")
#endif
#if __X64_BUILD__
#pragma comment(linker, "/EXPORT:VerQueryValueW=ASM_VerQueryValueW")
#else
#pragma comment(linker, "/EXPORT:VerQueryValueW=_ASM_VerQueryValueW@8")
#endif

// bind native dll first
extern void GetOrignalLibraryPath(TCHAR* bufferPtr, int bufferLength, const TCHAR* libName);

void __CheckedLoad()
{
    TCHAR szPath[MAX_PATH];

    GetOrignalLibraryPath(szPath, MAX_PATH, TEXT("version.dll"));

    // if your dll is not in system path
    // please reset szPath here
    HMODULE module = LoadLibrary(szPath);

    if (module == NULL)
    {
        TCHAR szMessage[MAX_PATH];
        wsprintf(szMessage, TEXT("Failed load dll from:%s"), szPath);
        MessageBox(0, szMessage, TEXT("AHeadLib.Net Error"), 0);
        
        ExitProcess(1);
        return;
    }

    GetFileVersionInfoAPtr = __CheckedGetFunction(module, "GetFileVersionInfoA");
    GetFileVersionInfoByHandlePtr = __CheckedGetFunction(module, "GetFileVersionInfoByHandle");
    GetFileVersionInfoExAPtr = __CheckedGetFunction(module, "GetFileVersionInfoExA");
    GetFileVersionInfoExWPtr = __CheckedGetFunction(module, "GetFileVersionInfoExW");
    GetFileVersionInfoSizeAPtr = __CheckedGetFunction(module, "GetFileVersionInfoSizeA");
    GetFileVersionInfoSizeExAPtr = __CheckedGetFunction(module, "GetFileVersionInfoSizeExA");
    GetFileVersionInfoSizeExWPtr = __CheckedGetFunction(module, "GetFileVersionInfoSizeExW");
    GetFileVersionInfoSizeWPtr = __CheckedGetFunction(module, "GetFileVersionInfoSizeW");
    GetFileVersionInfoWPtr = __CheckedGetFunction(module, "GetFileVersionInfoW");
    VerFindFileAPtr = __CheckedGetFunction(module, "VerFindFileA");
    VerFindFileWPtr = __CheckedGetFunction(module, "VerFindFileW");
    VerInstallFileAPtr = __CheckedGetFunction(module, "VerInstallFileA");
    VerInstallFileWPtr = __CheckedGetFunction(module, "VerInstallFileW");
    VerLanguageNameAPtr = __CheckedGetFunction(module, "VerLanguageNameA");
    VerLanguageNameWPtr = __CheckedGetFunction(module, "VerLanguageNameW");
    VerQueryValueAPtr = __CheckedGetFunction(module, "VerQueryValueA");
    VerQueryValueWPtr = __CheckedGetFunction(module, "VerQueryValueW");
}


