; generated by tools
; AHeadLib.Net
; https://github.com/bodong1987/AHeadLib.Net
; Powered by bodong

.MODEL FLAT

.DATA
    EXTERNDEF _GetFileVersionInfoAPtr:DWORD
    EXTERNDEF _GetFileVersionInfoByHandlePtr:DWORD
    EXTERNDEF _GetFileVersionInfoExAPtr:DWORD
    EXTERNDEF _GetFileVersionInfoExWPtr:DWORD
    EXTERNDEF _GetFileVersionInfoSizeAPtr:DWORD
    EXTERNDEF _GetFileVersionInfoSizeExAPtr:DWORD
    EXTERNDEF _GetFileVersionInfoSizeExWPtr:DWORD
    EXTERNDEF _GetFileVersionInfoSizeWPtr:DWORD
    EXTERNDEF _GetFileVersionInfoWPtr:DWORD
    EXTERNDEF _VerFindFileAPtr:DWORD
    EXTERNDEF _VerFindFileWPtr:DWORD
    EXTERNDEF _VerInstallFileAPtr:DWORD
    EXTERNDEF _VerInstallFileWPtr:DWORD
    EXTERNDEF _VerLanguageNameAPtr:DWORD
    EXTERNDEF _VerLanguageNameWPtr:DWORD
    EXTERNDEF _VerQueryValueAPtr:DWORD
    EXTERNDEF _VerQueryValueWPtr:DWORD

.CODE

_ASM_GetFileVersionInfoA@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoAPtr]
_ASM_GetFileVersionInfoA@8 ENDP

_ASM_GetFileVersionInfoByHandle@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoByHandlePtr]
_ASM_GetFileVersionInfoByHandle@8 ENDP

_ASM_GetFileVersionInfoExA@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoExAPtr]
_ASM_GetFileVersionInfoExA@8 ENDP

_ASM_GetFileVersionInfoExW@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoExWPtr]
_ASM_GetFileVersionInfoExW@8 ENDP

_ASM_GetFileVersionInfoSizeA@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoSizeAPtr]
_ASM_GetFileVersionInfoSizeA@8 ENDP

_ASM_GetFileVersionInfoSizeExA@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoSizeExAPtr]
_ASM_GetFileVersionInfoSizeExA@8 ENDP

_ASM_GetFileVersionInfoSizeExW@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoSizeExWPtr]
_ASM_GetFileVersionInfoSizeExW@8 ENDP

_ASM_GetFileVersionInfoSizeW@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoSizeWPtr]
_ASM_GetFileVersionInfoSizeW@8 ENDP

_ASM_GetFileVersionInfoW@8 PROC
    jmp DWORD PTR [_GetFileVersionInfoWPtr]
_ASM_GetFileVersionInfoW@8 ENDP

_ASM_VerFindFileA@8 PROC
    jmp DWORD PTR [_VerFindFileAPtr]
_ASM_VerFindFileA@8 ENDP

_ASM_VerFindFileW@8 PROC
    jmp DWORD PTR [_VerFindFileWPtr]
_ASM_VerFindFileW@8 ENDP

_ASM_VerInstallFileA@8 PROC
    jmp DWORD PTR [_VerInstallFileAPtr]
_ASM_VerInstallFileA@8 ENDP

_ASM_VerInstallFileW@8 PROC
    jmp DWORD PTR [_VerInstallFileWPtr]
_ASM_VerInstallFileW@8 ENDP

_ASM_VerLanguageNameA@8 PROC
    jmp DWORD PTR [_VerLanguageNameAPtr]
_ASM_VerLanguageNameA@8 ENDP

_ASM_VerLanguageNameW@8 PROC
    jmp DWORD PTR [_VerLanguageNameWPtr]
_ASM_VerLanguageNameW@8 ENDP

_ASM_VerQueryValueA@8 PROC
    jmp DWORD PTR [_VerQueryValueAPtr]
_ASM_VerQueryValueA@8 ENDP

_ASM_VerQueryValueW@8 PROC
    jmp DWORD PTR [_VerQueryValueWPtr]
_ASM_VerQueryValueW@8 ENDP


END

