; generated by tools
; AHeadLib.Net
; https://github.com/bodong1987/AHeadLib.Net
; Powered by bodong

.DATA
    EXTERNDEF GetFileVersionInfoAPtr:QWORD
    EXTERNDEF GetFileVersionInfoByHandlePtr:QWORD
    EXTERNDEF GetFileVersionInfoExAPtr:QWORD
    EXTERNDEF GetFileVersionInfoExWPtr:QWORD
    EXTERNDEF GetFileVersionInfoSizeAPtr:QWORD
    EXTERNDEF GetFileVersionInfoSizeExAPtr:QWORD
    EXTERNDEF GetFileVersionInfoSizeExWPtr:QWORD
    EXTERNDEF GetFileVersionInfoSizeWPtr:QWORD
    EXTERNDEF GetFileVersionInfoWPtr:QWORD
    EXTERNDEF VerFindFileAPtr:QWORD
    EXTERNDEF VerFindFileWPtr:QWORD
    EXTERNDEF VerInstallFileAPtr:QWORD
    EXTERNDEF VerInstallFileWPtr:QWORD
    EXTERNDEF VerLanguageNameAPtr:QWORD
    EXTERNDEF VerLanguageNameWPtr:QWORD
    EXTERNDEF VerQueryValueAPtr:QWORD
    EXTERNDEF VerQueryValueWPtr:QWORD

.CODE

ASM_GetFileVersionInfoA PROC
    jmp [GetFileVersionInfoAPtr]
ASM_GetFileVersionInfoA ENDP

ASM_GetFileVersionInfoByHandle PROC
    jmp [GetFileVersionInfoByHandlePtr]
ASM_GetFileVersionInfoByHandle ENDP

ASM_GetFileVersionInfoExA PROC
    jmp [GetFileVersionInfoExAPtr]
ASM_GetFileVersionInfoExA ENDP

ASM_GetFileVersionInfoExW PROC
    jmp [GetFileVersionInfoExWPtr]
ASM_GetFileVersionInfoExW ENDP

ASM_GetFileVersionInfoSizeA PROC
    jmp [GetFileVersionInfoSizeAPtr]
ASM_GetFileVersionInfoSizeA ENDP

ASM_GetFileVersionInfoSizeExA PROC
    jmp [GetFileVersionInfoSizeExAPtr]
ASM_GetFileVersionInfoSizeExA ENDP

ASM_GetFileVersionInfoSizeExW PROC
    jmp [GetFileVersionInfoSizeExWPtr]
ASM_GetFileVersionInfoSizeExW ENDP

ASM_GetFileVersionInfoSizeW PROC
    jmp [GetFileVersionInfoSizeWPtr]
ASM_GetFileVersionInfoSizeW ENDP

ASM_GetFileVersionInfoW PROC
    jmp [GetFileVersionInfoWPtr]
ASM_GetFileVersionInfoW ENDP

ASM_VerFindFileA PROC
    jmp [VerFindFileAPtr]
ASM_VerFindFileA ENDP

ASM_VerFindFileW PROC
    jmp [VerFindFileWPtr]
ASM_VerFindFileW ENDP

ASM_VerInstallFileA PROC
    jmp [VerInstallFileAPtr]
ASM_VerInstallFileA ENDP

ASM_VerInstallFileW PROC
    jmp [VerInstallFileWPtr]
ASM_VerInstallFileW ENDP

ASM_VerLanguageNameA PROC
    jmp [VerLanguageNameAPtr]
ASM_VerLanguageNameA ENDP

ASM_VerLanguageNameW PROC
    jmp [VerLanguageNameWPtr]
ASM_VerLanguageNameW ENDP

ASM_VerQueryValueA PROC
    jmp [VerQueryValueAPtr]
ASM_VerQueryValueA ENDP

ASM_VerQueryValueW PROC
    jmp [VerQueryValueWPtr]
ASM_VerQueryValueW ENDP


END

